name: RegionEdit
main: xyz.acrylicstyle.region.RegionEditPlugin
version: 0.1.10
author: acrylic-style
api-version: "1.13"
softdepend:
  - TomeitoLib
commands:
  sel:
    description: "Clears region selection."
    aliases: ["/sel", ";"]
  "/set":
    description: ""
    permission: regionedit.set
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/cut":
    description: ""
    permission: regionedit.cut
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/replace":
    description: ""
    aliases: ["/rep"]
    permission: regionedit.replace
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/limit":
    description: ""
    permission: regionedit.limit
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/drain":
    description: ""
    permission: regionedit.drain
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/pos1":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/hpos1":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/pos2":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/hpos2":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/expand":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/chunk":
    description: ""
    permission: regionedit.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/undo":
    description: ""
    permission: regionedit.undo
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/redo":
    description: ""
    permission: regionedit.redo
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/cancel":
    description: ""
    permission: regionedit.cancel
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  regionedit:
    description: "RegionEdit"
    aliases: ["/re", "re", "/regionedit"]
  "/help":
    description: ""
    permission: regionedit.help
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/fast":
    description: ""
    permission: regionedit.fast
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/unstuck":
    description: ""
    permission: regionedit.unstuck
    permission-message: "&cYou don't have permission. Are you in a right mode?"