name: RegionEdit
main: xyz.acrylicstyle.region.RegionEditPlugin
version: 0.0.10
author: acrylic-style
softdepend:
  - TomeitoLib
commands:
  sel:
    description: "Clears region selection."
    aliases: ["/sel", ";"]
  "/set":
    description: ""
    permission: regions.set
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/cut":
    description: ""
    permission: regions.cut
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/replace":
    description: ""
    aliases: ["/rep"]
    permission: regions.replace
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/limit":
    description: ""
    permission: regions.limit
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/drain":
    description: ""
    permission: regions.drain
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/pos1":
    description: ""
    permission: regions.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/hpos1":
    description: ""
    permission: regions.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/pos2":
    description: ""
    permission: regions.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/hpos2":
    description: ""
    permission: regions.selection
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/undo":
    description: ""
    permission: regions.undo
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/redo":
    description: ""
    permission: regions.redo
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  "/cancel":
    description: ""
    permission: regions.cancel
    permission-message: "&cYou don't have permission. Are you in a right mode?"
  regionedit:
    description: "RegionEdit"
    aliases: ["/re", "re", "/regionedit"]
  "/help":
    description: ""
    permission: regions.help
    permission-message: "&cYou don't have permission. Are you in a right mode?"